name: CI pride

on:
  push:
    branches: [main]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}  
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven
        run: mvn -B package -DskipTests

  docker:
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push image to Docker Hub
        run: |
          docker build -t leonardopradosptech/pitagoras:latest .
          docker push leonardopradosptech/pitagoras:latest

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: "44.217.150.7"
          username: "ubuntu"
          key: ${{ secrets.CHANGER }}
          script: |
            cd /home/ubuntu/
            ssh -i Changer.pem ubuntu@10.0.0.231
            sudo docker pull leonardopradosptech/pitagoras
            sudo docker run -p 80:80 -p 8080:8080 -p 443:443 -d leonardopradosptech/pitagoras

      - uses: appleboy/ssh-action@v1.0.3
        with:
          host: "44.217.150.7"
          username: "ubuntu"
          key: ${{ secrets.CHANGER }}
          script: |
            cd /home/ubuntu/
            ssh -i Changer.pem ubuntu@10.0.0.224
            sudo docker pull leonardopradosptech/pitagoras
            sudo docker run -p 80:80 -p 8080:8080 -p 443:443 -d leonardopradosptech/pitagoras